### PR TITLE
supporting mobile platform page validation

### PR DESCRIPTION
**Pull request by alizelzele**

### CODE REVIEW

**Review by mach6 — COMMENTED** [review]
@alizelzele I need you to rebase this please and push the update. I want to see the codacy results before merging.. Thanks!

**Review by mach6 — APPROVED** [review]
Pending rebase and codacy results, this change set LGTM

**Comment by alizelzele** [comment]
@mach6 i will update this PR, as soon as #315 is done.

**Comment by mach6** [comment]
@alizelzele #315 is now merged.

**Comment by alizelzele** [comment]
@mach6 ready to go ;)

**Comment by mach6** [comment]
@alizelzele merged .. thanks! also, fyi I don't think this change will require a doc update.

**Pull request merged**
