### PR TITLE
decrease test suite parameters

### PR DESCRIPTION
**Pull request by alizelzele**
1. removing mobilePlatform parameter and getting it from mobileTestSession
2. updating mobileDeviceType to be optional and can be resolved from mobileDevice

### CODE REVIEW

**Review by mach6 — APPROVED** [review]
LGTM

**Comment by mach6** [comment]
@alizelzele I need you to rebase this please and push the update. I want to see the codacy results before merging.. Thanks!

**Review by mach6 — COMMENTED** [review]
@alizelzele I need you to rebase this please and push the update. I want to see the codacy results before merging.. Thanks!

**Comment by alizelzele** [comment]
@mach6 rebased and pushed the changes on both pull requests.

btw, right now, my pull requests are getting divided into 2 different branches (develop, and develop-1.2), is there any schedule to merge these two branches soon?

**Comment by mach6** [comment]
@alizelzele anything merged to `develop-1.2.0` will make it to `develop`..  Which I admit is currently behind.. fixing that right now..... 

The branches won't be merging. `develop-1.2.0` is for bug fixes and is compatible with Selenium 2.53.x. `develop` is for new features (and all non-conflicting bug fixes that go into 1.2.0) and is compatible with Selenium 3.0.0 (currently beta)

**Comment by mach6** [comment]
@alizelzele rebase again please.. `develop` now also has your previously merged changes

**Comment by alizelzele** [comment]
@mach6 great, done.

**Comment by mach6** [comment]
@alizelzele please follow up with doc changes related to this change.

**Comment by alizelzele** [comment]
@mach6 sure, will do it asap.

**Comment by alizelzele** [comment]
@mach6 what an ASAP 😄 
updated documentation for parameters. https://github.com/paypal/SeLion/pull/335

**Pull request merged**
