### PR TITLE
Issue #323 - upgrade TestNG version to 6.9.12

### PR DESCRIPTION
**Pull request by ILikeToNguyen**

### CODE REVIEW

**Comment by ILikeToNguyen** [comment]
PR is not ready.  Worked in my local becuase testng 6.9.12 is in our companys maven repository but 6.9.11 and 6.9.12 is not published to maven central.  TestNG is now being pushed to jcenter.
http://testng.org/doc/download.html

Will update the PR with this added maven repository to our pom file.

**Comment by mach6** [comment]
@ILikeToNguyen which PR should we be looking at? this or #324

**Comment by ILikeToNguyen** [comment]
Yea I took an unorthodox approach.  Both PRs point to the same branch I have in my fork. I wanted to signify I wanted it applied to both develop branches so I created a PR against each develop branch.  I should just do 1 PR and put a comment that it should be applied to both develop branches instead of 2 PRs against each develop branch.  Closing 324.

**Review by mach6 — APPROVED** [review]
👍 LGTM ..

**Comment by mach6** [comment]
This needs to go into `2.0.0` also

**Pull request merged**
