### PR TITLE
Fix (issue #15) to remove the unwanted whitespace below the footer

### PR DESCRIPTION
**Pull request by sundaramrajendran**
This fix has been test with FireFox, Chrome, IE and Safari browsers

### CODE REVIEW

**Comment by sundaramrajendran** [comment]
@mach6 Addressed all the review comments.

**Comment by mach6** [comment]
@sundaramrajendran  The footer behavior in the PR for the documentation page is not what I had in mind. 

What I'm looking for is a footer that is always at the absolute bottom of the page -- like the home page -- not a "sticky" footer which is at the bottom of the view port.. In the later, the content above the footer is scrolled in the container div, and the footer remains.. In the former, the content above the footer is scrolled with the entire page. The footer will only be visible when the user scrolls to the bottom of the page.

**Comment by sundaramrajendran** [comment]
@mach6 I hope latest commit meets your requirement

**Comment by mach6** [comment]
@sundaramrajendran looks really good and such a simple fix too! very nice.

**Pull request merged**
