### PR TITLE
#128: Updated customCapabilities description

### PR DESCRIPTION
**Pull request by SudhakaraPeram**
#128: Updated customCapabilities description

### CODE REVIEW

**Comment by SudhakaraPeram** [comment]
@mach6 For some reason I'm not able to assign this pull request to you, can you please review the pull request and let me know if any changes required. Thanks!

**Comment by mach6** [comment]
@SudhakaraPeram Thank you for this.. 2 things.. 
1. Will you please sign the individual contributor CLA?
2. Will you please make a change which keeps the site content in sync with the javadoc comment for `customCapabilities`? -- https://github.com/paypal/SeLion/blob/develop/client/src/main/java/com/paypal/selion/configuration/Config.java#L439-L445  If you want to update the text in both locations, 2 Pull Requests since the code is in different branches, would be great.

**Comment by SudhakaraPeram** [comment]
@mach6 
1. Done
2. Submitted #136
Thanks!

**Comment by mach6** [comment]
Thx.. This looks good.. I'm going to make a minor tweak and merge this.

**Comment by mach6** [comment]
updated commit and merged this -- https://github.com/paypal/SeLion/commit/b2f4a52f827bc181bf1beb5983ebb258608fafba

**Pull request closed without merging**
