### PR TITLE
Adding capability to specify sdk version / device variation via Webtest ...

### PR DESCRIPTION
**Pull request by azaytsev**
...annotations. #57 

Addressing all the comments from the previous pull request.

### CODE REVIEW

**Comment by mach6** [comment]
@azaytsev I don't see international mountains added as a resource per a previous comment. did you decide to go a different route?

**Comment by azaytsev** [comment]
@mach6 Decided to do it as part of archetype update task #64. The branch for it is here. https://github.com/azaytsev/SeLion/commit/f1f0ec8dd4b00a0acdc712db80e00a2ee5258f30

I need to have this pull request merged before issuing one for #64 since it piggybacks on the changes in this request.

**Comment by mach6** [comment]
@azaytsev I don't follow the logic. How will the changes you made to `client/src/test/java/com/paypal/selion/ios/sample/NativeAppDemo.java` (which is not in the archetype) as part of this PR run if the apps are in the archetype?

**Comment by azaytsev** [comment]
@mach6 It won't. Maybe I should just delete this file and keep the one included with the archetype.

**Comment by krmahadevan** [comment]
@azaytsev 
I don't think that should be done. `NativeAppDemo` can be used as a functional test for SeLion `client` component. If you move it out, then how would one test out if SeLion Mobile support functionality works fine after some changes are made ? Please have the International mountains application be made as part of SeLion `src/test/resources`

**Comment by azaytsev** [comment]
done. added the app to src/test/resources/app folder

**Comment by mach6** [comment]
this is merged to develop

**Pull request closed without merging**
