### PR TITLE
Added documentation about the multiple ways to define additonal selen…

### PR DESCRIPTION
**Pull request by sundaramrajendran**
…ium capabilties

### CODE REVIEW

**Comment by mach6** [comment]
Looks good. I'm going to make some minor edits and merge this

**Comment by mach6** [comment]
@sundaramrajendran I made my edits. Please review, squash, and merge, if this looks good to you.

**Comment by sundaramrajendran** [comment]
@mach6 Looks better, I will merge.

**Comment by sundaramrajendran** [comment]
Merged

**Pull request closed without merging**
