### PR TITLE
Add capability of monitoring a native Android applications folder.

### PR DESCRIPTION
**Pull request by binhvu**
So these application can be retrieved, signed and added to the
app store by selendroid.

Signed-off-by: Binh Vu bvu@paypal.com

### CODE REVIEW

**Comment by mach6** [comment]
:+1: for this PR. 

However, I'm holding off on it until https://github.com/selendroid/selendroid/pull/712 which adds the `-folder` to Selendroid is merged and I can pull the updated Selendroid artifacts which contain the change from Maven Central.

**Comment by krmahadevan** [comment]
@mach6 
I am not sure if I am even supposed to add comments in the Selendroid codebase, but I did log a few comments myself :)

**Comment by mach6** [comment]
@krmahadevan Of course you are. Thanks!

**Comment by mach6** [comment]
@binhvu I need you to resubmit this PR. You killed your develop branch which contained the content.

**Pull request closed without merging**
