### PR TITLE
Fix #220 - appName and appPath processing bug

### LINKED ISSUE #220: String 'selion-hub-storage:' is not converted when mobile 'appPath' is provided outside the MobileTest annotation.
This logic only happens when the value is passed via the annotation;

https://github.com/paypal/SeLion/blob/develop/client/src/main/java/com/paypal/selion/internal/platform/grid/MobileTestSession.java#L180-L194

### PR DESCRIPTION
**Pull request by mach6**
Processing of appName and appPath in MobileTestSession was not
happening when values were passed as config properties

### CODE REVIEW

**Comment by mach6** [comment]
@sebady @sundaramrajendran any concerns with this?

**Comment by sundaramrajendran** [comment]
Looks good to me

**Comment by sebady** [comment]
This specific change looks fine.  I would also recommend fixing the use of this to be consistent.

There are more problems though in this initializeTestSession.
If the configuration for language was specified as "MOBILE_APP_LANGUAGE=fr" the method initializeTestSession will use "en" for lang instead since that is the default value in MobileTest annotation.

**Comment by mach6** [comment]
@sebady The problem you mention is due to the default value in `MobileTest` -- so we need to rethink that ... I don't see any inconsistency in `initializeTestSession` here w.r.t how things work in `WebTest`

**Comment by mach6** [comment]
@sebady @sundaramrajendran I believe I have addressed the review feedback and updated this PR. Please confirm

**Pull request merged**
