### PR TITLE
Added LICENSE to every SeLion jar file. Closes #108

### LINKED ISSUE #108: Add LICENSE file to resulting jars
The jar files should have a copy of the LICENSE file in them.

### PR DESCRIPTION
**Pull request by sundaramrajendran**

### CODE REVIEW

**Comment by mach6** [comment]
@sundaramrajendran What about the archetype and codegen artifacts? How about using maven to copy/create these resources instead of having multiple copies?

**Comment by sundaramrajendran** [comment]
@mach6 Addressed review comments

**Comment by mach6** [comment]
@sundaramrajendran this looks good to me.. The only change I'll suggest is to use `src/main/resources` everywhere.. You have mixed usage of `src\main\resources` and `src/main/resources`. Note: use of backslash vs. forwardslash

**Comment by sundaramrajendran** [comment]
@mach6 Done

**Pull request merged**
