### PR TITLE
fix UnixProcessHandler

### PR DESCRIPTION
**Pull request by sebady**
Fix the process termination on Unix to kill all browser/driver decendents
during process cleanup.

### CODE REVIEW

**Comment by mach6** [comment]
@sebady fyi, change causes a failure on travis ci.

**Comment by mach6** [comment]
@sebady Please update the copyright year on the two changed files.

**Comment by sebady** [comment]
i have update the copyrights

**Comment by mach6** [comment]
looks okay to me. feel free to merge please.

**Pull request merged**
